// Shared inline style tokens used across all components
export const T = {
    page: {
        width: "100%",
        minHeight: "100vh",
        background: "linear-gradient(170deg,#060818 0%,#0c0d2a 45%,#100825 100%)",
        color: "#dce8ff",
        fontFamily: "'Sora',sans-serif",
        position: "relative",
        overflowX: "hidden",
    },
    card: {
        background: "rgba(10,14,40,0.82)",
        border: "1px solid rgba(124,58,237,0.18)",
        borderRadius: 16,
        backdropFilter: "blur(14px)",
    },
    btn: {
        background: "linear-gradient(135deg,#7c3aed,#4f46e5)",
        color: "white",
        border: "none",
        borderRadius: 10,
        padding: "12px 28px",
        fontFamily: "'Sora',sans-serif",
        fontWeight: 700,
        fontSize: 14,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    ghost: {
        background: "rgba(124,58,237,0.1)",
        color: "#a78bfa",
        border: "1px solid rgba(124,58,237,0.3)",
        borderRadius: 10,
        padding: "10px 22px",
        fontFamily: "'Sora',sans-serif",
        fontWeight: 600,
        fontSize: 13,
        cursor: "pointer",
        transition: "all 0.2s",
    },
    inp: {
        background: "rgba(255,255,255,0.04)",
        border: "1px solid rgba(124,58,237,0.25)",
        borderRadius: 10,
        padding: "13px 16px",
        color: "#dce8ff",
        fontFamily: "'JetBrains Mono',monospace",
        fontSize: 14,
        width: "100%",
        outline: "none",
        transition: "border-color 0.2s",
        resize: "vertical",
    },
};
