'use strict';

const { Router } = require('express');
const { query } = require('../config/db');
const firebaseAuth = require('../middleware/firebaseAuth');

const router = Router();

// ─── POST /api/v1/auth/sync ───────────────────────────────────────────────────
// Called by the frontend immediately after Firebase login.
// Ensures the user exists in our PostgreSQL `users` table.
//
// FIX: The `users.id` column is UUID (auto-generated by Postgres).
// We must NOT insert the Firebase string UID as the id.
// Instead we upsert by EMAIL and let Postgres generate the UUID.
router.post('/sync', firebaseAuth, async (req, res) => {
    const { email, name } = req.user;

    try {
        // Generate a unique username: display name or email prefix + random suffix
        const baseUsername = name || email.split('@')[0];
        const suffix = Math.floor(1000 + Math.random() * 9000); // 4-digit random
        const fallbackUsername = `${baseUsername}_${suffix}`;

        // Upsert by email — let Postgres auto-generate the UUID id.
        // ON CONFLICT (email) → user already exists, just return their row.
        const result = await query(
            `INSERT INTO users (username, email)
             VALUES ($1, $2)
             ON CONFLICT (email) DO UPDATE
               SET updated_at = NOW()
             RETURNING id, username, email, created_at`,
            [fallbackUsername, email]
        );

        const user = result.rows[0];
        return res.status(200).json({ user });
    } catch (err) {
        // If the random username collided with an existing one, retry once
        if (err.code === '23505' && err.constraint?.includes('username')) {
            try {
                const baseUsername = name || email.split('@')[0];
                const suffix = Math.floor(10000 + Math.random() * 90000);
                const retryUsername = `${baseUsername}_${suffix}`;
                const result = await query(
                    `INSERT INTO users (username, email)
                     VALUES ($1, $2)
                     ON CONFLICT (email) DO UPDATE
                       SET updated_at = NOW()
                     RETURNING id, username, email, created_at`,
                    [retryUsername, email]
                );
                return res.status(200).json({ user: result.rows[0] });
            } catch (retryErr) {
                console.error('[Auth /sync] Retry DB error:', retryErr.message);
                return res.status(500).json({ error: 'Internal Server Error' });
            }
        }
        console.error('[Auth /sync] DB error:', err.message);
        return res.status(500).json({ error: 'Internal Server Error' });
    }
});

// ─── GET /api/v1/users/me ─────────────────────────────────────────────────────
// Returns the authenticated user's profile + mastery snapshot.
// Used to populate the TopBar XP pill.
//
// FIX: Look up by email (from the Firebase token), NOT by Firebase UID,
// because the Postgres id is a UUID, not the Firebase string UID.
router.get('/me', firebaseAuth, async (req, res) => {
    const { email } = req.user;

    try {
        const result = await query(
            `SELECT
               u.id, u.username, u.email, u.created_at,
               s.current_level, s.cached_total_xp, s.concept_debt_score, s.last_recalculated_at
             FROM users u
             LEFT JOIN user_mastery_snapshot s ON s.user_id = u.id
             WHERE u.email = $1`,
            [email]
        );

        if (result.rows.length === 0) {
            return res.status(404).json({ error: 'User not found' });
        }

        return res.status(200).json({ user: result.rows[0] });
    } catch (err) {
        console.error('[Auth /me] DB error:', err.message);
        return res.status(500).json({ error: 'Internal Server Error' });
    }
});

module.exports = router;
